/**
 * Phase 12: Financial Statements Master Data
 *
 * Authoritative statement definitions matching the organisation's prescribed format from:
 * reference/Format of Balance sheet , IE and schedules1.xlsx
 *
 * Preserves:
 * - Exact Statement Headings
 * - Exact Major Sections & Subsections
 * - Exact Line Item Labels, Numbering and Display Orders
 * - Exact Note References (Notes 4 through 33)
 * - Exact Sign Conventions and Hierarchy
 */

export type StatementCode = 'BS' | 'IE';

export type StatementSectionType =
  | 'LIABILITIES'
  | 'ASSETS'
  | 'INCOME'
  | 'EXPENSES'
  | 'RESULT';

export type StatementLineType =
  | 'SECTION_HEADER'
  | 'SUBSECTION_HEADER'
  | 'GROUP_HEADER'
  | 'LINE_ITEM'
  | 'SUBTOTAL'
  | 'TOTAL';

export type StatementSourceType =
  | 'NOTE'
  | 'NOTE_PORTION'
  | 'REPORTING_NODE'
  | 'FSLI'
  | 'CALCULATED'
  | 'SUBTOTAL'
  | 'TOTAL'
  | 'HEADER';

export interface StatementLineDefinition {
  statementLineId: string;
  statementCode: StatementCode;
  section: StatementSectionType;
  subSection?: string;
  lineIndex?: string;
  lineLabel: string;
  lineType: StatementLineType;
  sourceType: StatementSourceType;
  sourceNoteNumber?: number;
  sourceScheduleCode?: string;
  sourceNodeCodes?: string[];
  notePortionKey?: string; // 'NON_CURRENT' | 'CURRENT' | 'NET_ASSET' | 'DEPRECIATION'
  calculationMethod?: string;
  parentLineId?: string;
  displayOrder: number;
  depth: number;
  cyRequired: boolean;
  pyRequired: boolean;
  noteReference?: string | number;
}

export interface FinancialStatementDefinition {
  statementCode: StatementCode;
  title: string;
  sections: StatementSectionType[];
  lines: StatementLineDefinition[];
}

/**
 * Authoritative Balance Sheet Statement Line Definitions
 * Sourced directly from workbook: "Balance sheet" sheet
 */
export const BALANCE_SHEET_LINE_DEFINITIONS: StatementLineDefinition[] = [
  // ── LIABILITIES ─────────────────────────────────────────────────────────────
  {
    statementLineId: 'bs-hdr-liab',
    statementCode: 'BS',
    section: 'LIABILITIES',
    lineLabel: 'LIABILITIES',
    lineType: 'SECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 1,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },

  // Subsection: Capital and Reserve
  {
    statementLineId: 'bs-sub-cap-res',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Capital and Reserve',
    lineLabel: 'Capital and Reserve',
    lineType: 'SUBSECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 2,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-liab-04',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Capital and Reserve',
    lineIndex: '(a)',
    lineLabel: 'Corpus',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 4,
    sourceScheduleCode: 'SCH_04',
    noteReference: 4,
    displayOrder: 3,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-liab-05',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Capital and Reserve',
    lineIndex: '(b)',
    lineLabel: 'Reserves and surplus',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 5,
    sourceScheduleCode: 'SCH_05',
    noteReference: 5,
    displayOrder: 4,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },

  // Subsection: Non-Current Liabilities
  {
    statementLineId: 'bs-sub-ncl',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Non-Current Liabilities',
    lineLabel: 'Non-Current Liabilities',
    lineType: 'SUBSECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 5,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-liab-06-nc',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Non-Current Liabilities',
    lineIndex: '(a)',
    lineLabel: 'Secured loans',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 6,
    sourceScheduleCode: 'SCH_06',
    notePortionKey: 'NON_CURRENT',
    noteReference: 6,
    displayOrder: 6,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-liab-07',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Non-Current Liabilities',
    lineIndex: '(b)',
    lineLabel: 'Unsecured Loans',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 7,
    sourceScheduleCode: 'SCH_07',
    noteReference: 7,
    displayOrder: 7,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },

  // Subsection: Current liabilities and Provisions
  {
    statementLineId: 'bs-sub-clp',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Current liabilities and Provisions',
    lineLabel: 'Current liabilities and Provisions',
    lineType: 'SUBSECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 8,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-liab-06-c',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Current liabilities and Provisions',
    lineIndex: '(a)',
    lineLabel: 'Short Term Borrowings',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 6,
    sourceScheduleCode: 'SCH_06',
    notePortionKey: 'CURRENT',
    noteReference: 6,
    displayOrder: 9,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-liab-08',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Current liabilities and Provisions',
    lineIndex: '(b)',
    lineLabel: 'Sundry Creditors',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 8,
    sourceScheduleCode: 'SCH_08',
    noteReference: 8,
    displayOrder: 10,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-liab-09',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Current liabilities and Provisions',
    lineIndex: '(c)',
    lineLabel: 'Other current liabilities',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 9,
    sourceScheduleCode: 'SCH_09',
    noteReference: 9,
    displayOrder: 11,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-liab-10',
    statementCode: 'BS',
    section: 'LIABILITIES',
    subSection: 'Current liabilities and Provisions',
    lineIndex: '(d)',
    lineLabel: 'Short-term liabilities and provisions',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 10,
    sourceScheduleCode: 'SCH_10',
    noteReference: 10,
    displayOrder: 12,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },

  // Total Liabilities
  {
    statementLineId: 'bs-tot-liab',
    statementCode: 'BS',
    section: 'LIABILITIES',
    lineLabel: 'TOTAL',
    lineType: 'TOTAL',
    sourceType: 'TOTAL',
    calculationMethod: 'SUM_LIABILITIES',
    displayOrder: 13,
    depth: 0,
    cyRequired: true,
    pyRequired: true,
  },

  // ── ASSETS ──────────────────────────────────────────────────────────────────
  {
    statementLineId: 'bs-hdr-ast',
    statementCode: 'BS',
    section: 'ASSETS',
    lineLabel: 'ASSETS',
    lineType: 'SECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 14,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },

  // Subsection: Non-Current Assets
  {
    statementLineId: 'bs-sub-nca',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineLabel: 'Non-Current Assets',
    lineType: 'SUBSECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 15,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-grp-ppe-intang',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(a)',
    lineLabel: 'Property ,Plant & Equipmnts & Intangible assets',
    lineType: 'GROUP_HEADER',
    sourceType: 'HEADER',
    displayOrder: 16,
    depth: 1,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-ast-11',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(i)',
    lineLabel: 'Propery, Plant & Equipment',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 11,
    sourceScheduleCode: 'SCH_11',
    notePortionKey: 'NET_ASSET',
    noteReference: 11,
    displayOrder: 17,
    depth: 2,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-intang',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(ii)',
    lineLabel: 'Intangible',
    lineType: 'LINE_ITEM',
    sourceType: 'REPORTING_NODE',
    sourceNodeCodes: ['N_11_INTANG'],
    displayOrder: 18,
    depth: 2,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-12',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(iii)',
    lineLabel: 'Capital Work in Progress',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 12,
    sourceScheduleCode: 'SCH_12',
    noteReference: 12,
    displayOrder: 19,
    depth: 2,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-13',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(iv)',
    lineLabel: 'Live Stock',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 13,
    sourceScheduleCode: 'SCH_13',
    noteReference: 13,
    displayOrder: 20,
    depth: 2,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-16',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(b)',
    lineLabel: 'Investments',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 16,
    sourceScheduleCode: 'SCH_16',
    noteReference: 16,
    displayOrder: 21,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-18-nc',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Non-Current Assets',
    lineIndex: '(d)',
    lineLabel: 'Other Non-currents assets',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 18,
    sourceScheduleCode: 'SCH_18',
    notePortionKey: 'NON_CURRENT',
    noteReference: 18,
    displayOrder: 22,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },

  // Subsection: Current assets
  {
    statementLineId: 'bs-sub-ca',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineLabel: 'Current assets',
    lineType: 'SUBSECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 23,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'bs-ast-14',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineIndex: '(a)',
    lineLabel: 'Trade Receivables',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 14,
    sourceScheduleCode: 'SCH_14',
    noteReference: 14,
    displayOrder: 24,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-15',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineIndex: '(b)',
    lineLabel: 'Cash and Bank Balances',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 15,
    sourceScheduleCode: 'SCH_15',
    noteReference: 15,
    displayOrder: 25,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-17',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineIndex: '(c)',
    lineLabel: 'Inventories',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 17,
    sourceScheduleCode: 'SCH_17',
    noteReference: 17,
    displayOrder: 26,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-18-c',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineIndex: '(d)',
    lineLabel: 'Short-term loans and advances',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 18,
    sourceScheduleCode: 'SCH_18',
    notePortionKey: 'CURRENT',
    noteReference: 18,
    displayOrder: 27,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'bs-ast-19',
    statementCode: 'BS',
    section: 'ASSETS',
    subSection: 'Current assets',
    lineIndex: '(e)',
    lineLabel: 'Other Current Assets',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 19,
    sourceScheduleCode: 'SCH_19',
    noteReference: 19,
    displayOrder: 28,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },

  // Total Assets
  {
    statementLineId: 'bs-tot-ast',
    statementCode: 'BS',
    section: 'ASSETS',
    lineLabel: 'TOTAL',
    lineType: 'TOTAL',
    sourceType: 'TOTAL',
    calculationMethod: 'SUM_ASSETS',
    displayOrder: 29,
    depth: 0,
    cyRequired: true,
    pyRequired: true,
  },
];

/**
 * Authoritative Statement of Income and Expenditure Line Definitions
 * Sourced directly from workbook: "Income and Expenditure" sheet
 */
export const INCOME_EXPENDITURE_LINE_DEFINITIONS: StatementLineDefinition[] = [
  // ── INCOME ──────────────────────────────────────────────────────────────────
  {
    statementLineId: 'ie-hdr-inc',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'INCOME',
    lineType: 'SECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 1,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'ie-inc-20',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Donations and Grant in Aid',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 20,
    sourceScheduleCode: 'SCH_20',
    noteReference: 20,
    displayOrder: 2,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-inc-21',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Donations for Scientific and Industrial, Social Research',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 21,
    sourceScheduleCode: 'SCH_21',
    noteReference: 21,
    displayOrder: 3,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-inc-22',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Revenue from operations',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 22,
    sourceScheduleCode: 'SCH_22',
    noteReference: 22,
    displayOrder: 4,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-inc-23',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Agriculture, Dairy Income',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 23,
    sourceScheduleCode: 'SCH_23',
    noteReference: 23,
    displayOrder: 5,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-inc-24',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Other income',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 24,
    sourceScheduleCode: 'SCH_24',
    noteReference: 24,
    displayOrder: 6,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-inc-25',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Increase (decrease) in Finished Goods, Trading items',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 25,
    sourceScheduleCode: 'SCH_25',
    noteReference: 25,
    calculationMethod: 'SIGNED_STOCK_MOVEMENT',
    displayOrder: 7,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-tot-rev',
    statementCode: 'IE',
    section: 'INCOME',
    lineLabel: 'Total revenue',
    lineType: 'SUBTOTAL',
    sourceType: 'SUBTOTAL',
    calculationMethod: 'SUM_REVENUE',
    displayOrder: 8,
    depth: 0,
    cyRequired: true,
    pyRequired: true,
  },

  // ── EXPENSES ────────────────────────────────────────────────────────────────
  {
    statementLineId: 'ie-hdr-exp',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'EXPENSES',
    lineType: 'SECTION_HEADER',
    sourceType: 'HEADER',
    displayOrder: 9,
    depth: 0,
    cyRequired: false,
    pyRequired: false,
  },
  {
    statementLineId: 'ie-exp-26',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Community Welfare, Charitable Application',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 26,
    sourceScheduleCode: 'SCH_26',
    noteReference: 26,
    displayOrder: 10,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-27',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Application for Social & Scientific Research ',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 27,
    sourceScheduleCode: 'SCH_27',
    noteReference: 27,
    displayOrder: 11,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-28',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Consumption of material, stores and others',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 28,
    sourceScheduleCode: 'SCH_28',
    noteReference: 28,
    displayOrder: 12,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-29',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Cost of Trading Items sold',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 29,
    sourceScheduleCode: 'SCH_29',
    noteReference: 29,
    displayOrder: 13,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-30',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Agriculture, Dairy Expense',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 30,
    sourceScheduleCode: 'SCH_30',
    noteReference: 30,
    displayOrder: 14,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-31',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Employees Benefits Expenses',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 31,
    sourceScheduleCode: 'SCH_31',
    noteReference: 31,
    displayOrder: 15,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-32',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Finance costs',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 32,
    sourceScheduleCode: 'SCH_32',
    noteReference: 32,
    displayOrder: 16,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-11',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Depreciation and amortization expense',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE_PORTION',
    sourceNoteNumber: 11,
    sourceScheduleCode: 'SCH_11',
    notePortionKey: 'DEPRECIATION',
    noteReference: 11,
    displayOrder: 17,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-exp-33',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Administrative and Other Expenses',
    lineType: 'LINE_ITEM',
    sourceType: 'NOTE',
    sourceNoteNumber: 33,
    sourceScheduleCode: 'SCH_33',
    noteReference: 33,
    displayOrder: 18,
    depth: 1,
    cyRequired: true,
    pyRequired: true,
  },
  {
    statementLineId: 'ie-tot-exp',
    statementCode: 'IE',
    section: 'EXPENSES',
    lineLabel: 'Total expenses',
    lineType: 'SUBTOTAL',
    sourceType: 'SUBTOTAL',
    calculationMethod: 'SUM_EXPENSES',
    displayOrder: 19,
    depth: 0,
    cyRequired: true,
    pyRequired: true,
  },

  // ── RESULT / SURPLUS ────────────────────────────────────────────────────────
  {
    statementLineId: 'ie-surplus-deficit',
    statementCode: 'IE',
    section: 'RESULT',
    lineLabel: 'Surplus/(Deficit) for the year',
    lineType: 'TOTAL',
    sourceType: 'TOTAL',
    calculationMethod: 'NET_SURPLUS_DEFICIT',
    displayOrder: 20,
    depth: 0,
    cyRequired: true,
    pyRequired: true,
  },
];

export const STATEMENT_DEFINITIONS: Record<StatementCode, FinancialStatementDefinition> = {
  BS: {
    statementCode: 'BS',
    title: 'Balance Sheet',
    sections: ['LIABILITIES', 'ASSETS'],
    lines: BALANCE_SHEET_LINE_DEFINITIONS,
  },
  IE: {
    statementCode: 'IE',
    title: 'Statement of Income and Expenditure',
    sections: ['INCOME', 'EXPENSES', 'RESULT'],
    lines: INCOME_EXPENDITURE_LINE_DEFINITIONS,
  },
};
